<?php

declare(strict_types=1);

/**
 * import-rule-numbers.php — regenerate config/rule_numbers.php from the
 * official SATUSEHAT error dictionary CSV.
 *
 * Usage:
 *   php scripts/import-rule-numbers.php
 *   php scripts/import-rule-numbers.php --source=/path/to/Dokumen Kamus Rule Number (Error Code) - V2.0.csv
 *
 * The generated file is committed (drop-in deployments have no runtime CSV
 * dependency). Re-run whenever Kemenkes publishes a new dictionary version.
 */

$root = dirname(__DIR__);
$source = '/home/malifnasrulloh/Downloads/satu-sehat-postman/[PUBLISHED] Dokumen Kamus Rule Number (Error Code) - V2.0.csv';
foreach (array_slice($argv, 1) as $arg) {
    if (str_starts_with($arg, '--source=')) {
        $source = substr($arg, strlen('--source='));
    }
}

if (!is_file($source)) {
    fwrite(STDERR, "Source CSV not found: {$source}\n");
    exit(2);
}

$fh = fopen($source, 'r');
$header = fgetcsv($fh);
if ($header === false) {
    fwrite(STDERR, "Cannot read CSV header\n");
    exit(2);
}

$rules = [];
$skipped = 0;
while (($row = fgetcsv($fh)) !== false) {
    $no = (int) ($row[0] ?? 0);
    $desc = trim((string) ($row[3] ?? ''));
    $term = trim((string) ($row[2] ?? ''));
    if ($no <= 0) {
        $skipped++;
        continue;
    }
    if ($desc === '') {
        $desc = $term;
    }
    $rules[$no] = $desc;
}
fclose($fh);

if (empty($rules)) {
    fwrite(STDERR, "No rules parsed — wrong source file?\n");
    exit(2);
}
ksort($rules);

$out = "<?php\n\n/**\n * RuleNumber dictionary — generated by scripts/import-rule-numbers.php\n * from the official SATUSEHAT error dictionary (Kamus Rule Number V2.0).\n * Do not edit by hand; re-run the importer after dictionary updates.\n */\n\nreturn " . var_export($rules, true) . ";\n";
file_put_contents($root . '/config/rule_numbers.php', $out);

fwrite(STDOUT, "Imported " . count($rules) . " rules (skipped {$skipped} header/empty rows) -> config/rule_numbers.php\n");
exit(0);
